# The language to output bindings in
language = "C++"

# Options for wrapping the contents of the header:
include_guard = "OPENCOMPGRAPH_CBINDGEN_H"

# Whether to include a comment with the version of cbindgen used to
# generate the file
include_version = true

# An optional list of namespaces to output around the generated bindings
namespaces = ["open_comp_graph", "cbindgen"]

# A list of headers to #include (with quotes)
includes = ["symbol_export.h"]

# Whether to make a C header C++ compatible.
# These will wrap generated functions into a `extern "C"` block, e.g.
cpp_compat = true

# The desired length of a line to use when formatting lines
line_length = 80

# The amount of spaces to indent by
tab_width = 2

# Codegen Options

[export]
# A list of items to not include in the generated bindings
exclude = ["SharedThing", "run_sharedthing", "get_name", "make_thingc"]
